
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build on Node.js 16.13.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - run: npm install
        working-directory: ./cobra-app-workspace